# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CS 241 - System Programming
email: angrave@illinois.edu
description: > # this means to ignore newlines until "baseurl:"
  Webpage for CS241.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://illinois-cs241.github.io" # the base hostname & protocol for your site
repository: illinois-cs241/illinois-cs241.github.io
github_username: illinois-cs241

# Build settings
markdown: kramdown

gems:
 - jemoji
